#!/usr/bin/python3

import re
import sys

if "--help" in sys.argv:
    print("List of Arguments:\n --help:         displays this list\n --no-recur:     forces program to run only one cycle regardless of 'recur' configuration\n --reset-config: resets the config file to defaults\n --settings:     runs the settings menu")
    sys.exit(0)

from cdrmodules import main
