#!/usr/bin/python3
"""
    Copyright (C) 2020-present, Murdo B. Maclachlan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.
    
    Contact me at murdo@maclachlans.org.uk
"""

import re
import sys

if "--help" in sys.argv:
    print("List of Arguments:\n --format-cdr:   rename old .cdremover directories, etc. to fit OSCR's new name\n --help:         displays this list\n --no-recur:     forces program to run only one cycle regardless of 'recur' configuration\n --reset-config: resets the config file to defaults\n --settings:     runs the settings menu")
    sys.exit(0)

print(
      "Copyright (C) 2020-present, Murdo B. Maclachlan\n"
      "This program comes with ABSOLUTELY NO WARRANTY.\n"
      "This is free software, and you are welcome to redistribute it\n"
      "under certain conditions; see LICENCE in dist-info for conditions."
)

from oscrmodules import main
