#!/usr/bin/python3
"""
    Copyright (C) 2020-present, Murdo B. Maclachlan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.
    
    Contact me at murdo@maclachlans.org.uk
"""

from oscrmodules.globals import initialiseGlobals, VERSION
from oscrmodules.misc import getConfig
from oscrmodules.arguments import checkArgs

print(
      "Copyright (C) 2020-present, Murdo B. Maclachlan\n"
      "This program comes with ABSOLUTELY NO WARRANTY.\n"
      "This is free software, and you are welcome to redistribute it\n"
      "under certain conditions; see LICENCE in dist-info for conditions."
)

Globals = checkArgs(getConfig(initialiseGlobals(VERSION)))

from oscrmodules.main import oscr

oscr(Globals)
